# Generated by Django 5.1.2 on 2024-11-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_alter_project_options_remove_material_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('industrial', 'Industrial')], default=0, max_length=20),
            preserve_default=False,
        ),
    ]
