# Generated by Django 5.1.2 on 2024-11-01 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_project_project_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='area_size',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Area size in square meters', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='elements',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
