# Generated by Django 5.1.2 on 2024-11-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0005_remove_project_elements_project_project_element'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_element',
            field=models.CharField(choices=[('exterior_wall_framing', 'Exterior Wall Framing'), ('roof_framing', 'Roof Framing'), ('door_framing', 'Door Framing'), ('barn_door', 'Barn Door'), ('sliding_door', 'Sliding Door'), ('light_switches', 'Light Switches'), ('main_panel', 'Main Panel'), ('shower_fixture', 'Shower Fixture'), ('toilet_installation', 'Toilet Installation')], max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('framing', 'Framing'), ('window_and_door_installation', 'Window and Door Installation'), ('electrical', 'Electrical'), ('plumbing', 'Plumbing')], max_length=100),
        ),
    ]
