# Generated by Django 5.1.2 on 2024-11-01 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0008_material_markup_percentage_material_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectelement',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='projectelement',
            name='unit_price',
        ),
        migrations.CreateModel(
            name='ElementMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('markup_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.material')),
                ('project_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.projectelement')),
            ],
        ),
        migrations.AddField(
            model_name='projectelement',
            name='materials',
            field=models.ManyToManyField(through='quotes.ElementMaterial', to='quotes.material'),
        ),
    ]
