# Generated by Django 5.1.2 on 2024-11-01 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0009_remove_projectelement_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('markup_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.material')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='materials',
            field=models.ManyToManyField(through='quotes.ProjectMaterial', to='quotes.material'),
        ),
    ]
