# Generated by Django 5.1.2 on 2024-11-02 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0011_project_admin_approved_project_admin_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('completed', 'Completed'), ('pending', 'Pending Admin Review'), ('quoted', 'Quotation Provided'), ('approved', 'Approved by Admin'), ('declined', 'Declined by Admin'), ('approved', 'Approved by Customer'), ('declined', 'Declined by Customer')], default='pending', max_length=20),
        ),
    ]
