# Generated by Django 5.1.2 on 2024-11-02 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0012_alter_project_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='completion_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='area_size',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotation',
            name='customer',
            field=models.ForeignKey(default=256, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotation',
            name='description',
            field=models.TextField(default=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotation',
            name='location',
            field=models.CharField(default=8, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotation',
            name='project_element',
            field=models.CharField(choices=[('exterior_wall_framing', 'Exterior Wall Framing'), ('roof_framing', 'Roof Framing'), ('door_framing', 'Door Framing'), ('barn_door', 'Barn Door'), ('sliding_door', 'Sliding Door'), ('light_switches', 'Light Switches'), ('main_panel', 'Main Panel'), ('shower_fixture', 'Shower Fixture'), ('toilet_installation', 'Toilet Installation')], default=7, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotation',
            name='project_type',
            field=models.CharField(choices=[('framing', 'Framing'), ('window_and_door_installation', 'Window and Door Installation'), ('electrical', 'Electrical'), ('plumbing', 'Plumbing')], default=6, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotation',
            name='title',
            field=models.CharField(default=3, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='QuotationMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('markup', models.DecimalField(decimal_places=2, max_digits=5)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.material')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.quotation')),
            ],
            options={
                'unique_together': {('quotation', 'material')},
            },
        ),
        migrations.AddField(
            model_name='quotation',
            name='materials',
            field=models.ManyToManyField(through='quotes.QuotationMaterial', to='quotes.material'),
        ),
    ]
