# Generated by Django 5.1.2 on 2024-11-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0015_quotation_status_quotation_total_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='area_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
