# Generated by Django 5.1.2 on 2024-11-02 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0017_projectmaterial_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='additional_markup',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='quotation',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='quotation',
            name='labor_costs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='quotation',
            name='materials_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='quotation',
            name='service_fees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pending_review', 'Pending Admin Review'), ('quoted', 'Quotation Provided'), ('approved_admin', 'Approved by Admin'), ('approved_customer', 'Approved by Customer'), ('declined_admin', 'Declined by Admin'), ('declined_customer', 'Declined by Customer'), ('completed', 'Completed'), ('pending_admin_review', 'Pending Admin Review')], default='pending', max_length=20),
        ),
    ]
