# Generated by Django 5.1.2 on 2024-11-02 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0018_quotation_additional_markup_quotation_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='additional_markup_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='quotation',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
