# Generated by Django 5.1.2 on 2024-11-02 21:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0019_quotation_additional_markup_percentage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='quotation',
            constraint=models.UniqueConstraint(fields=('project',), name='unique_active_quotation_per_project'),
        ),
    ]
